version: "3.9"

services:
  web:
    build: .
    ports:
      - "5003:5003"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5440:5433"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
